### ISSUE TITLE
The links appear not to work

### ISSUE THREAD

**Issue by dominikglodzikhms** [hms-dbmi/chromoscope#107]
I generated a link from the following sample:
![Screen Shot 2023-05-03 at 5 00 25 PM](https://user-images.githubusercontent.com/82227017/236048526-5e04e0c0-b515-470f-a37a-ff50c7960eb0.png)

[This is the link](https://chromoscope.bio/?demoIndex=13&domain=262199043.2088271-511449663.20882684)

However, upon clicking, it takes me to another sample

**Comment by sehilyi** [comment]
The `external=` parameter seems to be missing.
